CREATE TABLE minions (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR (50) NOT NULL,
	age INT NULL
);

CREATE TABLE towns (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR (50) NOT NULL	
);

