CREATE DATABASE library;
USE library;
CREATE TABLE authors(
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL
);

CREATE TABLE books(
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50),
	author_id INT NOT NULL,
	CONSTRAINT fk_author_id 
	FOREIGN KEY(author_id) REFERENCES authors(id)
	ON DELETE CASCADE
);